app:
  container_name: app
  build: .
  ports:
    - "8070:80"
  volumes:
    - .:/var/www/
    - ./logs/:/var/log/apache2
  links:
    - mysql:mysql

mysql:
  container_name: mysql
  restart: always
  image: mysql:5.6
  mem_limit: 128m
  ports:
    - "3306:3306"
  volumes_from:
    - data
data:
  container_name: data
  image: busybox
  volumes:
    - /var/lib/mysql